### ISSUE TITLE
register password validator shows pw in cleartext

### ISSUE THREAD

**Issue by JensTimmerman** [ZeusWPI/zauth#123]
![image](https://user-images.githubusercontent.com/281523/134922078-5e8eaf4f-95fd-4ddb-b865-e7454c538fb5.png)

**Comment by wschella** [comment]
I came across this as well with @iasoon and forgot to make an issue.

The responsible library is https://github.com/Keats/validator . There a way to set the message string with the `message` argument of the macro, but it's not super flexible. Can be used to solve the issue tho.

**Comment by rien** [comment]
There was already an issue for this (#87), but this is something we should have fixed earlier. Thanks for the PR!
