### ISSUE TITLE
Show proper error when registering with a duplicate username/email

### ISSUE THREAD

**Issue by Tibo-Ulens** [ZeusWPI/zauth#177]
Currently, when attempting to create a new account with a username or email that is already in use, zauth shows the "Not Acceptable" error page.
It would be better if this would simply redirect back to the register page with an error along the lines of "username/email is already in use".
This might not have a straightforward solution though seeing as diesels errors when violating a constraint are rather verbose. They tend to be something along the lines of "duplicate key violates unique constraint "{table}\_{field_name}\_key" "
The best idea i've had so far is to extract the constraint name from the errors information field, split it on '_' and take the 2nd value (field_name). This could be done in the errors module by creating a new error type (say DuplicateError) and with a simple addition to the From\<diesel::result::Error\> implementation, but it isn't particularly clean.

**Comment by rien** [comment]
I think the proper way to fix this, is to check validations also at the application level. The database constraint is still needed though, because such a check would not be atomic.

**Comment by Tibo-Ulens** [comment]
Checking them at the application level as in, running queries to find if a user with that username/email already exists? That would work obviously but i feel it's a bit wasteful to run extra queries when diesel already (badly) tells you what went wrong.
Or did i misinterpret your solution, that's always possible.
Either way, if you'd like i can try making a PR for this sometime after the break.

**Comment by rien** [comment]
I'm not really convinced that this can be done "clean" by trying to parse the error string and I think this application should be optimized for readability and maintenance. Database performance is currently not an issue.

We already have a system in place currently to perform validations and there is an extra database lookup there: https://github.com/ZeusWPI/zauth/blob/cf785ca8ac50174ab01b041687587cbfe5921dd9/src/models/user.rs#L318-L335

But if we would be adding extra validations needing the database, we should probably put those in a separate function with a [custom validator](https://github.com/Keats/validator#custom).

I will gladly accept a PR if you want to make one :smiley:

**Comment by ninewise** [comment]
Correct error code would be a 403 (forbidden) rather than a 406 (not acceptable) anyway.

**Comment by Tibo-Ulens** [comment]
Would it not be better to use either 409 (Conflict) or 422 (Unprocessable Entity) for this? 403 implies more that a user doesn't have permission to make that request

**Comment by ninewise** [comment]
409 would work, too. 422 is for semantic errors, which I don't think this is. The request would have correct syntax and semantics.

**Comment by rien** [comment]
The 406 error is indeed incorrect here (and probably a bug), it is most likely generated here: https://github.com/ZeusWPI/zauth/blob/main/src/views/accepter.rs#L43 but I don't know what caused is. Normally, this should be an internal server error.

There is [some discussion over the best HTTP code for validation errors]. The popular web framework rails (which is kind of the inspiration for this project) uses 422. This is not ideal since one could consider the semantics of such a request to be correct, but I think it is useful to have a distinct error code for these kind of errors. So I would personally prefer 422.

**Comment by Tibo-Ulens** [comment]
the request returns a 500 error code, the [500 error page](https://github.com/ZeusWPI/zauth/blob/main/templates/errors/500.html) contains the text "Not Acceptable" so it doesn't even return a 406, it just presents a 500 as a 406

**Comment by rien** [comment]
Oh :sweat_smile: 

Well, that needs to be changed then.
