### ISSUE TITLE
Implement simple mailing list functionality

### ISSUE THREAD

**Issue by redfast00** [ZeusWPI/zauth#217]
We would like to replace mailman (our mailing list program), ideally without having to hook zauth to another maling list program.  A minimum viable solution would be able to send an email, composed in Zauth, to all subscribed members; members subscribe by default.

Note that this avoids several 'hard' components:

- you don't have to receive email and forward it; you can just compose the email in Zauth
- you don't have to have a rich email composer in the frontend; this is just plain text

I understand that this feels like feature creep: a mailing list doesn't have anything to do with the authentication system. It would however make our lives much easier than yet another microservice.

**Comment by rien** [comment]
We would lose the ability to let members send mails to the mailinglist with this functionality.

But it is definitely doable to implement a notification service (with the option to unsubscribe).
