### ISSUE TITLE
Username capitalized

### ISSUE THREAD

**Issue by Topvennie** [ZeusWPI/zauth#259]
Gebruikersnamen startend met een hoofdletter zijn momenteel niet toegelaten.
Momenteel krijg je ook een regex error message als je een aacount probeert te maken startend met een hoofdletter

**Comment by redfast00** [comment]
(zie ook https://github.com/ZeusWPI/zauth/issues/87)

**Comment by redfast00** [comment]
Ik denk wel dat we best geen hoofdletters in usernames toelaten
