### ISSUE TITLE
Same full name makes it impossible to accept the user

### ISSUE THREAD

**Issue by Topvennie** [ZeusWPI/zauth#293]
If an user has the same full name as an already existing user, the new users appears in the already accepted users list. Their status shows "email confirmation pending". 
However the mail is never sent as the user isn't actually accepted.

**Comment by rien** [comment]
That is weird, the full name should never be used to find users in the database, and to my knowledge there is no uniqueness check on it.

I would guess something else went wrong (maybe with the mailer?) causing the acceptance flow to break down.

In any case, I don't seem to have permissions to examine the logs for this particular case.

**Comment by xerbalind** [comment]
was indeed an issue with the mailer
