### ISSUE TITLE
Transitieplan

### ISSUE THREAD

**Issue by redfast00** [ZeusWPI/zauth#33]
# Transitieplan

## Huidige services

- mails: Via postfix komen deze binnen, dan worden ze opgezocht in LDAP en geforward naar het correcte emailadres
- oauth: users kunnen inloggen

## Constraints

- Emailsysteem mag niet lang down zijn, ideaal niet langer dan een `systemctl reload postfix`
- Login mag wel even down zijn
- We moeten de bestaande users/emailcombinaties houden

## Plan

- [x] Zauth opzetten op adams
- [ ] Usernames/emailaddressen importeren van LDAP naar zauth
- [ ] Postfix config veranderen zodat het de usernames opzoekt in de database in plaats van op LDAP. Doe dit met comments, zodat als dit niet werkt, we dit makkelijk kunnen terugrollen. Stuur een testmail.
- [ ] Nginx config schrijven voor zauth, `rewrite` gebruiken om ervoor te zorgen dat de oude API-configs blijven werken
- [x] Zauth live brengen
- [ ] Mail sturen naar elke gebruiker dat hun wachtwoord gereset is, annoucement maken dat wachtwoorden gereset zijn

**Comment by JensTimmerman** [comment]
an update on this?

**Comment by redfast00** [comment]
Alles is gebeurd
