### ISSUE TITLE
Admins should be able to "activate" users

### ISSUE THREAD

**Issue by rien** [ZeusWPI/zauth#39]
- There should be an overview of all pending users
- Clicking an "approve" button should send an email welcoming them and asking them to confirm their email.
- A new user state should be added, saying the user's email is not yet activated. Maybe `pending` should be split into `pending_activation` and `pending_email`?

**Comment by rien** [comment]
Alternatively we could also add a separate email confirmation flow.

**Comment by wschella** [comment]
If both an admin confirming the user, and the user confirming the e-mail need to happen, it seems `pending` needs to be split.

Is there a reason users can't confirm their e-mail before admin approval?

**Comment by rien** [comment]
> If both an admin confirming the user, and the user confirming the e-mail need to happen, it seems `pending` needs to be split.
:+1: 

> Is there a reason users can't confirm their e-mail before admin approval?
- Less mail for the user. Only one email should be sent "You have been approved, finish your registration by confirming your email by clicking  _this_ link."
- If each registration requests sends an email, we've opened up a way to send emails to arbitrary mail addresses without admin approval. It seams more secure to wait for an admin to explicitly approve a user's email before sending something.

**Comment by wschella** [comment]
Makes sense!

**Comment by mcbloch** [comment]
I'd think `pending_approval` and `pending_mail_confirmation` are bit more descriptive no?

**Comment by mcbloch** [comment]
Do we want to have the approval button in the list with all users?

Do we want a separate page for approving users or is a separate table on the users page also good?
