### ISSUE TITLE
Rewrite in Elixir/Phoenix?

### ISSUE THREAD

**Issue by rien** [ZeusWPI/zauth#70]
So the Zauth project has been dragging on for a while now, and is not even usable currently. Some roadblocks we are experiencing right now:
- The Diesel ORM is very barebones and there isn't an alternative (that I know of) that has less boilerplate, so we have a lot of very similar codepaths in the models.
- Rocket has no support for CSRF tokens. There is a [rocket_csrf](https://github.com/Plume-org/rocket_csrf) library that implements them by parsing the body manually and then **rewriting** it. So it is wonky and not usable for production.
- Rust's ecosystem for web applications is in general not very mature. A few things have to be implemented manually which you would expect to be just there, but maybe that is me being spoiled by Ruby-on-Rails.

While I am still convinced an authentication server in Rust is a good idea, I also think our time is limited so we need rapid development tools, which Rust is not.

So I am proposing (and poking for some opinions) to rewrite the Zeus authentication server in Elixir with the [Phoenix framework](https://www.phoenixframework.org/). I see the following improvements:
- Better ORM and overall rapid-prototyping
- Built-in security protections (forgery protection etc.)
- There is a lot of knowledge available in Zeus

The downside is of course that we 'lose' all the work we've put in the current Zauth version. I would personally not mind switching, but it is of course a big setback for the project and we need to make sure our progress in Elixir will be faster and less painful then it is now.

What are the opinions here? Are there people that would jump-in when a Elixir rewrite would happen? The decision is not yet been made, but I think it is a good time to evaluate whether we are on the good path.

**Comment by fbegyn** [comment]
Just my 2 cents.

I support the Diesel ORM and Rust web ecosystem remarks. In my limited experience both points are valid.

Both Rust and Elixir are on my *wanted langauges list*, but the amount of Rust magic that happens makes it a very had project to step into (even with some previous programming language) IMHO. With an Elixir rewrite, I'd be willing to jump-in. Previous test runs with the elixir/phoenix framework were pretty satisfying and fairly easy to set up/start with.

**Comment by VandorpeDavid** [comment]
What exactly are the required (core and additional) functionalities of this project?

**Comment by redfast00** [comment]
For Zeus, scalability is not really an issue (we don't have a lot of users and our users don't frequently use the endpoints). However, if this were to be used outside of Zeus, it might become a point of attention.

**Comment by maartenvn** [comment]
Since this project will be used for a long time (hopefully), I have some remarks on maintainability:
* How easy is it to install locally, without using a Dockerfile (which can be tedious to use during development)?
* How easy is it to upgrade to future versions?
* How easy is it to setup with an older, outdated, version? (is there some sort of version manager?)
Asking these questions as some Zeus Projects like Tab and Tap, written in Ruby can be hard to install locally, because older versions of Ruby aren't accessible (easily) anymore.

I want to contribute to the front-end of zAuth and write some beautiful (hopefully) CSS, if that is something you guys are looking for :smile:

**Comment by redfast00** [comment]
@maartenvn off-topic, but the ruby versions for Tab/Tab can be pretty easily managed/installed with something like [asdf](https://github.com/asdf-vm/asdf). This also supports Node, Elixir, ... A full list of plugins is available at https://asdf-vm.com/#/plugins-all

**Comment by rien** [comment]
Maybe one day someone will decide a rewrite in elixir is appropriate, but let us go with the sunken cost fallacy and stay with Rust for now.
