### ISSUE TITLE
Replace `wait_for_service` script by docker `depends_on`

### ISSUE THREAD

**Issue by maartenvn** [ZeusWPI/zauth#96]
Currently there is a `wait_for_service` script which waits on the database to get online before starting the container.
This is the same behavior as the docker-compose key `depends_on`.

**Comment by maartenvn** [comment]
I see the `depends_on` field is already present in the compose file. Is there a specific reason the `wait_for_service` script is still present?

**Comment by rien** [comment]
The database takes a few seconds before it is available, after the container has started. So I think `wait_for_service` just waits until the database binds itself to the specified port.

**Comment by maartenvn** [comment]
Maybe this can be done using the build in `healthcheck` in docker compose? https://docs.docker.com/compose/compose-file/compose-file-v2/#healthcheck
